version: "3.8"

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: login_db
      MYSQL_USER: loginuser
      MYSQL_PASSWORD: loginpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    restart: always
    ports:
      - "8081:5000"
    environment:
      DB_HOST: mysql
      DB_USER: loginuser
      DB_PASSWORD: loginpass
      DB_NAME: login_db
    depends_on:
      - mysql

volumes:
  mysql_data:
